# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 434d14f866f03b0fa2f55776b24321f1747bc15fbbc5893441bc5e9eeca36a7843ba52924742ba6aac6e8078fe0635ad88a8fbc8d83fe2a167d07f8a63d15561

test:
  secret_key_base: 1ff21d9946b89582ebc0916be58849c004a7dc00dbed71f9d800b576e9f0b0c2964aea4a334e938da540533f31a23117cc15756e4b8c33fb77c2f56f5d48b964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
